### ISSUE TITLE
Euler X angle not supported

### ISSUE THREAD

**Issue by heewoonam** [deNsuh/toonDra#31]
How to solve this to recognize whether head is up/down?

**Comment by heewoonam** [comment]
Alternate: detection을 켜면 몇초간(e.g. 3초간) 정면을 쳐다보게 한다. 이때 계산된 eye~nose까지 y거리를 기준으로 잡아 짧고 길어지는 거로 euler x angle을 estimate

**Comment by dansuh17** [comment]
Euler X가 고개를 위아래로 움직이는걸 detect하는건가요? Euler Y 랑 Z는 서포트 되나용?

**Comment by heewoonam** [comment]
네 그림에서 Roll = Euler Z, Yaw = Euler Y, Pitch = Euler X입니다. Y랑 Z는 정면 얼굴 대칭 정도로 계산할 수 있는데 X는 depth를 알아야돼서... OpenCV의 예제들을 보면 사람 얼굴 depth 평균값, 머신러닝, 또는 얼굴 정면 사진을 기준으로 계산합니다.
![fig-1-orientation-of-the-head-in-terms-of-pitch-roll-and-yaw-movements-describing](https://cloud.githubusercontent.com/assets/19640165/20054150/f166169a-a51e-11e6-84ed-1ed9eb07966a.png)

**Comment by dansuh17** [comment]
흐음
그러면 스크롤링 시작하기 전에 일종의 calibration이 필요하겠넴 ㅠㅠ 말한대로 머리의 세로 길이를 기준으로 그 길이를 대조시켜도 괜찮을거 같고
아니면 아예 Euler X를 안쓰는 방법도 있지 않을까??

**Comment by heewoonam** [comment]
Euler X를 안쓰면 YZ로 구현한다는 말이야?
내일 만나서 얘기하는거로 합시다

**Comment by heewoonam** [comment]
Used blink/wink.
